### ISSUE TITLE
Error 401 (OAuth2 Error)

### ISSUE THREAD

**Issue by cjds** [KFrazer/SmartAlarm#1]
After the installation the error says that : 
Haven't changed any settings. Can you double check if it works on your machine

401
Error: deleted_client

The OAuth client was deleted.

The closest that I found to this was [this](http://stackoverflow.com/questions/21881031/google-cloud-platform-api-the-oauth-client-was-deleted-error)

**Comment by KFrazer** [comment]
Turns out the hardcoded google api secret in the python script got changed. I pulled the data from their api console again and it is now working.
