### ISSUE TITLE
Google Credentials visible

### ISSUE THREAD

**Issue by GelosSnake** [KFrazer/SmartAlarm#2]
Hey buddy,

Great project, however I've noticed that your google api creds are visible. 
Probably want to delete this and reset your api key:
client_id = '27689042960-3e573n9cu3c3sdguk4l6nrdgi8i4des7.apps.googleusercontent.com'
client_secret = 'SHfaJI6K8XJbKfhgZcoKfv4t'

**Comment by KFrazer** [comment]
Thanks!
